<a href="https://colab.research.google.com/github/DaniRodri17/dep/blob/main/keras_classification_penguin_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error
from sklearn.ensemble import RandomForestClassifier

In [5]:
df = pd.read_csv('penguins_size.csv')
df.head()

  species     island  culmen_length_mm  ...  flipper_length_mm  body_mass_g     sex
0  Adelie  Torgersen              39.1  ...              181.0       3750.0    MALE
1  Adelie  Torgersen              39.5  ...              186.0       3800.0  FEMALE
2  Adelie  Torgersen              40.3  ...              195.0       3250.0  FEMALE
3  Adelie  Torgersen               NaN  ...                NaN          NaN     NaN
4  Adelie  Torgersen              36.7  ...              193.0       3450.0  FEMALE

[5 rows x 7 columns]

In [17]:
df.dropna(inplace=True)

In [123]:
X = df.drop('species', axis=1)
y = df['species']

# Apply one-hot encoding to categorical columns 'island' and 'sex'
X = pd.get_dummies(X, columns=['island', 'sex'], dtype='int', drop_first=True)

# Convert target variable 'species' to one-hot encoded format
y = pd.get_dummies(y,  dtype='int',)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [124]:
dt = RandomForestClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
print(accuracy_score(y_test, dt_pred))

0.9900990099009901

In [127]:
from sklearn.metrics import classification_report
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        49
           1       1.00      0.94      0.97        18
           2       1.00      1.00      1.00        34

   micro avg       0.99      0.99      0.99       101
   macro avg       0.99      0.98      0.99       101
weighted avg       0.99      0.99      0.99       101
 samples avg       0.99      0.99      0.99       101

In [131]:
X_train.head()

     culmen_length_mm  culmen_depth_mm  ...  sex_FEMALE  sex_MALE
292              48.2             15.6  ...           0         1
302              47.4             14.6  ...           1         0
62               37.6             17.0  ...           1         0
181              52.8             20.0  ...           0         1
15               36.6             17.8  ...           1         0

[5 rows x 8 columns]

In [129]:
model = Sequential([
    Dense(512, activation='relu', input_shape=(8,)),
    Dense(312, activation='relu'),

    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['precision']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [130]:
history = model.fit(x=X_train, y=y_train,
                    validation_data=(X_test, y_test),
                    batch_size=10,
                    epochs=200)

Epoch 1/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 199.8436 - precision: 0.3377 - val_loss: 81.5512 - val_precision: 0.3366
Epoch 2/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.3130 - precision: 0.5202 - val_loss: 9.5301 - val_precision: 0.1782
Epoch 3/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20.5229 - precision: 0.3865 - val_loss: 25.2713 - val_precision: 0.4851
Epoch 4/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.1041 - precision: 0.4033 - val_loss: 33.6111 - val_precision: 0.3663
Epoch 5/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.2488 - precision: 0.4156 - val_loss: 27.6817 - val_precision: 0.1782
Epoch 6/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 24.3596 - precision: 0.3731 - val_loss: 26.4403 - val_precision: 0.1782
Epoch 7/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.9475 - precision: 0.3584 - val_loss: 40.1805 - val_precision: 0.1782
Epoch 8/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 32.6376 - precision: 0.4222 - val_loss: 14.6733 - val_precision: 0.1782
Epoch 9/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.2173 - precision: 0.4212 - val_loss: 21.9312 - val_precision: 0.3366
Epoch 10/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33.7439 - precision: 0.4063 - val_loss: 42.4673 - val_precision: 0.7129
Epoch 11/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 41.4273 - precision: 0.4004 - val_loss: 22.5241 - val_precision: 0.4752
Epoch 12/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7270 - precision: 0.5975 - val_loss: 33.6244 - val_precision: 0.3366
Epoch 13/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 37.6792 - precision: 0.3443 - val_loss: 27.1311 - val_precision: 0.2178
Epoch 14/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.7612 - precision: 0.4332 - val_loss: 43.7027 - val_precision: 0.3366
Epoch 15/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.6750 - precision: 0.4956 - val_loss: 23.3455 - val_precision: 0.3564
Epoch 16/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.0341 - precision: 0.4735 - val_loss: 2.7577 - val_precision: 0.7327
Epoch 17/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0503 - precision: 0.5585 - val_loss: 3.0750 - val_precision: 0.7228
Epoch 18/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.7759 - precision: 0.5102 - val_loss: 10.5125 - val_precision: 0.4950
Epoch 19/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.0851 - precision: 0.5040 - val_loss: 7.3382 - val_precision: 0.7129
Epoch 20/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11.0123 - precision: 0.5652 - val_loss: 41.5502 - val_precision: 0.1980
Epoch 21/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 35.7512 - precision: 0.3924 - val_loss: 21.2905 - val_precision: 0.4950
Epoch 22/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.0712 - precision: 0.6003 - val_loss: 46.3617 - val_precision: 0.3366
Epoch 23/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.5192 - precision: 0.4414 - val_loss: 12.1228 - val_precision: 0.4455
Epoch 24/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.3192 - precision: 0.5142 - val_loss: 3.8839 - val_precision: 0.7129
Epoch 25/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5177 - precision: 0.5927 - val_loss: 1.1503 - val_precision: 0.7624
Epoch 26/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.2401 - precision: 0.6337 - val_loss: 10.1746 - val_precision: 0.4851
Epoch 27/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.7743 - precision: 0.5667 - val_loss: 4.0459 - val_precision: 0.7624
Epoch 28/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.7427 - precision: 0.6385 - val_loss: 16.8601 - val_precision: 0.2079
Epoch 29/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.7302 - precision: 0.4818 - val_loss: 25.2335 - val_precision: 0.4752
Epoch 30/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.1146 - precision: 0.4486 - val_loss: 14.1312 - val_precision: 0.4257
Epoch 31/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.6829 - precision: 0.5583 - val_loss: 3.9196 - val_precision: 0.6634
Epoch 32/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9373 - precision: 0.5538 - val_loss: 17.1267 - val_precision: 0.3960
Epoch 33/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.8896 - precision: 0.5921 - val_loss: 10.4342 - val_precision: 0.6931
Epoch 34/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.8404 - precision: 0.5998 - val_loss: 16.1145 - val_precision: 0.4851
Epoch 35/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.2138 - precision: 0.4559 - val_loss: 30.6208 - val_precision: 0.3564
Epoch 36/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.3886 - precision: 0.4685 - val_loss: 2.3412 - val_precision: 0.7228
Epoch 37/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.9880 - precision: 0.6174 - val_loss: 5.0876 - val_precision: 0.6040
Epoch 38/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.2309 - precision: 0.5676 - val_loss: 11.9808 - val_precision: 0.6931
Epoch 39/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.5296 - precision: 0.5924 - val_loss: 5.1955 - val_precision: 0.7426
Epoch 40/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.7604 - precision: 0.6987 - val_loss: 1.7156 - val_precision: 0.6535
Epoch 41/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1053 - precision: 0.6635 - val_loss: 9.0562 - val_precision: 0.5050
Epoch 42/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7769 - precision: 0.5869 - val_loss: 10.1216 - val_precision: 0.6337
Epoch 43/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.0239 - precision: 0.6113 - val_loss: 1.6486 - val_precision: 0.6931
Epoch 44/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.2025 - precision: 0.6060 - val_loss: 1.6117 - val_precision: 0.8317
Epoch 45/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.9476 - precision: 0.5979 - val_loss: 4.0850 - val_precision: 0.6040
Epoch 46/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.0803 - precision: 0.5970 - val_loss: 12.8920 - val_precision: 0.2178
Epoch 47/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 11.0251 - precision: 0.5002 - val_loss: 16.4615 - val_precision: 0.3960
Epoch 48/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 12.1077 - precision: 0.5142 - val_loss: 4.0958 - val_precision: 0.7723
Epoch 49/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.2894 - precision: 0.6188 - val_loss: 2.7528 - val_precision: 0.4851
Epoch 50/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 4.1660 - precision: 0.6034 - val_loss: 9.1793 - val_precision: 0.4950
Epoch 51/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.8103 - precision: 0.6487 - val_loss: 6.8324 - val_precision: 0.3861
Epoch 52/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.2308 - precision: 0.5619 - val_loss: 2.6264 - val_precision: 0.5149
Epoch 53/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.7327 - precision: 0.7206 - val_loss: 3.5365 - val_precision: 0.6931
Epoch 54/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.2725 - precision: 0.6679 - val_loss: 3.1749 - val_precision: 0.7129
Epoch 55/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.2306 - precision: 0.6758 - val_loss: 2.2029 - val_precision: 0.5842
Epoch 56/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4424 - precision: 0.7443 - val_loss: 4.9275 - val_precision: 0.7624
Epoch 57/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.6480 - precision: 0.6861 - val_loss: 6.8644 - val_precision: 0.2871
Epoch 58/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.9547 - precision: 0.5575 - val_loss: 1.9842 - val_precision: 0.5248
Epoch 59/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2827 - precision: 0.7144 - val_loss: 2.6430 - val_precision: 0.6436
Epoch 60/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8888 - precision: 0.6339 - val_loss: 1.8369 - val_precision: 0.7327
Epoch 61/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2663 - precision: 0.7228 - val_loss: 3.1852 - val_precision: 0.5149
Epoch 62/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.7712 - precision: 0.6357 - val_loss: 1.7146 - val_precision: 0.7921
Epoch 63/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.3443 - precision: 0.6511 - val_loss: 3.8890 - val_precision: 0.7723
Epoch 64/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8369 - precision: 0.7018 - val_loss: 2.1190 - val_precision: 0.7525
Epoch 65/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.2689 - precision: 0.7016 - val_loss: 1.4987 - val_precision: 0.8119
Epoch 66/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1819 - precision: 0.8254 - val_loss: 0.3686 - val_precision: 0.9505
Epoch 67/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.4251 - precision: 0.7033 - val_loss: 2.0337 - val_precision: 0.5800
Epoch 68/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.7005 - precision: 0.7356 - val_loss: 0.8341 - val_precision: 0.7921
Epoch 69/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.4800 - precision: 0.7381 - val_loss: 12.5333 - val_precision: 0.4653
Epoch 70/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.2327 - precision: 0.6520 - val_loss: 0.5238 - val_precision: 0.9406
Epoch 71/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.3890 - precision: 0.6665 - val_loss: 4.6431 - val_precision: 0.6931
Epoch 72/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.6186 - precision: 0.7464 - val_loss: 0.9220 - val_precision: 0.7822
Epoch 73/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9101 - precision: 0.8067 - val_loss: 0.9378 - val_precision: 0.7200
Epoch 74/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0784 - precision: 0.7572 - val_loss: 0.4511 - val_precision: 0.8911
Epoch 75/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5928 - precision: 0.8750 - val_loss: 0.6520 - val_precision: 0.8218
Epoch 76/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7550 - precision: 0.8447 - val_loss: 0.4418 - val_precision: 0.8416
Epoch 77/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.3631 - precision: 0.7731 - val_loss: 0.7755 - val_precision: 0.8000
Epoch 78/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.6347 - precision: 0.6608 - val_loss: 0.5262 - val_precision: 0.9109
Epoch 79/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.5704 - precision: 0.6473 - val_loss: 0.5743 - val_precision: 0.8614
Epoch 80/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.8908 - precision: 0.8234 - val_loss: 2.3821 - val_precision: 0.7822
Epoch 81/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.3374 - precision: 0.7276 - val_loss: 0.5773 - val_precision: 0.8713
Epoch 82/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.5840 - precision: 0.7321 - val_loss: 1.4580 - val_precision: 0.7624
Epoch 83/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3130 - precision: 0.8160 - val_loss: 3.0867 - val_precision: 0.7327
Epoch 84/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.1869 - precision: 0.7234 - val_loss: 1.0408 - val_precision: 0.7624
Epoch 85/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6986 - precision: 0.7227 - val_loss: 3.3088 - val_precision: 0.4200
Epoch 86/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.3549 - precision: 0.6336 - val_loss: 0.9860 - val_precision: 0.8020
Epoch 87/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4422 - precision: 0.7700 - val_loss: 0.5490 - val_precision: 0.8713
Epoch 88/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.5846 - precision: 0.7514 - val_loss: 0.6134 - val_precision: 0.8911
Epoch 89/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6087 - precision: 0.8364 - val_loss: 1.1518 - val_precision: 0.8020
Epoch 90/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0149 - precision: 0.8711 - val_loss: 0.4596 - val_precision: 0.8812
Epoch 91/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1888 - precision: 0.6502 - val_loss: 10.7254 - val_precision: 0.5149
Epoch 92/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1722 - precision: 0.7493 - val_loss: 1.0695 - val_precision: 0.8515
Epoch 93/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7242 - precision: 0.8212 - val_loss: 0.2006 - val_precision: 0.9604
Epoch 94/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.8893 - precision: 0.7188 - val_loss: 1.3334 - val_precision: 0.7723
Epoch 95/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5117 - precision: 0.7500 - val_loss: 0.3399 - val_precision: 0.9406
Epoch 96/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7137 - precision: 0.8702 - val_loss: 2.1536 - val_precision: 0.5900
Epoch 97/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.8870 - precision: 0.7469 - val_loss: 3.1402 - val_precision: 0.5149
Epoch 98/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.4881 - precision: 0.6341 - val_loss: 3.3046 - val_precision: 0.6139
Epoch 99/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4374 - precision: 0.6205 - val_loss: 0.3302 - val_precision: 0.9406
Epoch 100/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3184 - precision: 0.8688 - val_loss: 0.3519 - val_precision: 0.9010
Epoch 101/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.9723 - precision: 0.9097 - val_loss: 0.4146 - val_precision: 0.9010
Epoch 102/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0527 - precision: 0.8119 - val_loss: 1.3087 - val_precision: 0.7624
Epoch 103/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 2.2066 - precision: 0.7127 - val_loss: 6.4269 - val_precision: 0.5050
Epoch 104/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.5872 - precision: 0.5069 - val_loss: 4.0969 - val_precision: 0.5941
Epoch 105/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6803 - precision: 0.8067 - val_loss: 0.3713 - val_precision: 0.8911
Epoch 106/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0891 - precision: 0.7212 - val_loss: 1.3543 - val_precision: 0.8119
Epoch 107/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3010 - precision: 0.7874 - val_loss: 1.5887 - val_precision: 0.8119
Epoch 108/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8770 - precision: 0.8230 - val_loss: 0.7712 - val_precision: 0.8614
Epoch 109/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0301 - precision: 0.6957 - val_loss: 1.1191 - val_precision: 0.8020
Epoch 110/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.3522 - precision: 0.7367 - val_loss: 0.9633 - val_precision: 0.8119
Epoch 111/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.4062 - precision: 0.7079 - val_loss: 2.2033 - val_precision: 0.7723
Epoch 112/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.6050 - precision: 0.6523 - val_loss: 3.5571 - val_precision: 0.5248
Epoch 113/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.3185 - precision: 0.7738 - val_loss: 0.4544 - val_precision: 0.8614
Epoch 114/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.5538 - precision: 0.7522 - val_loss: 2.9376 - val_precision: 0.7921
Epoch 115/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0620 - precision: 0.7574 - val_loss: 1.3327 - val_precision: 0.6800
Epoch 116/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1994 - precision: 0.7589 - val_loss: 0.5363 - val_precision: 0.8416
Epoch 117/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4419 - precision: 0.8865 - val_loss: 0.6233 - val_precision: 0.8812
Epoch 118/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7139 - precision: 0.8129 - val_loss: 0.7546 - val_precision: 0.7600
Epoch 119/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6617 - precision: 0.8090 - val_loss: 0.3074 - val_precision: 0.8713
Epoch 120/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2424 - precision: 0.9119 - val_loss: 1.3777 - val_precision: 0.7822
Epoch 121/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.6678 - precision: 0.7352 - val_loss: 1.9411 - val_precision: 0.6139
Epoch 122/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.6007 - precision: 0.6679 - val_loss: 0.1301 - val_precision: 0.9604
Epoch 123/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7598 - precision: 0.8409 - val_loss: 1.1255 - val_precision: 0.8119
Epoch 124/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9170 - precision: 0.8672 - val_loss: 0.1178 - val_precision: 0.9802
Epoch 125/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1566 - precision: 0.9500 - val_loss: 0.3414 - val_precision: 0.9406
Epoch 126/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.6009 - precision: 0.7829 - val_loss: 2.4770 - val_precision: 0.7525
Epoch 127/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.4164 - precision: 0.7287 - val_loss: 0.8130 - val_precision: 0.8317
Epoch 128/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5069 - precision: 0.8499 - val_loss: 0.1794 - val_precision: 0.9406
Epoch 129/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3691 - precision: 0.8915 - val_loss: 0.1378 - val_precision: 0.9604
Epoch 130/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2253 - precision: 0.9337 - val_loss: 0.4703 - val_precision: 0.8020
Epoch 131/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2256 - precision: 0.9119 - val_loss: 0.5058 - val_precision: 0.8600
Epoch 132/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0878 - precision: 0.7592 - val_loss: 0.1415 - val_precision: 0.9604
Epoch 133/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5188 - precision: 0.7820 - val_loss: 0.4808 - val_precision: 0.8119
Epoch 134/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6712 - precision: 0.8243 - val_loss: 0.1963 - val_precision: 0.9208
Epoch 135/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2309 - precision: 0.9436 - val_loss: 0.3923 - val_precision: 0.9208
Epoch 136/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7789 - precision: 0.8173 - val_loss: 2.8504 - val_precision: 0.7129
Epoch 137/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1196 - precision: 0.8244 - val_loss: 0.2836 - val_precision: 0.8911
Epoch 138/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8388 - precision: 0.8132 - val_loss: 0.1112 - val_precision: 0.9802
Epoch 139/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2208 - precision: 0.9360 - val_loss: 0.1919 - val_precision: 0.9505
Epoch 140/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1925 - precision: 0.7661 - val_loss: 0.4860 - val_precision: 0.8416
Epoch 141/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0413 - precision: 0.7754 - val_loss: 0.3296 - val_precision: 0.8812
Epoch 142/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5732 - precision: 0.7871 - val_loss: 0.1161 - val_precision: 0.9505
Epoch 143/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4145 - precision: 0.8550 - val_loss: 0.7022 - val_precision: 0.8218
Epoch 144/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5903 - precision: 0.7225 - val_loss: 0.2705 - val_precision: 0.8911
Epoch 145/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4040 - precision: 0.8609 - val_loss: 0.0621 - val_precision: 0.9802
Epoch 146/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6747 - precision: 0.8679 - val_loss: 0.4330 - val_precision: 0.8614
Epoch 147/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7260 - precision: 0.7894 - val_loss: 0.3534 - val_precision: 0.8812
Epoch 148/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.5307 - precision: 0.8660 - val_loss: 0.1507 - val_precision: 0.9505
Epoch 149/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4352 - precision: 0.8621 - val_loss: 0.6964 - val_precision: 0.7525
Epoch 150/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1141 - precision: 0.7709 - val_loss: 0.1482 - val_precision: 0.9505
Epoch 151/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4552 - precision: 0.8802 - val_loss: 0.1162 - val_precision: 0.9703
Epoch 152/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.5656 - precision: 0.8776 - val_loss: 0.3604 - val_precision: 0.9307
Epoch 153/200