<a href="https://colab.research.google.com/github/DaniRodri17/dep/blob/main/keras_project_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import os
import PIL
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import pandas as pd

In [5]:
df = pd.read_csv('StudentPerformanceFactors.csv')
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('Exam_Score', axis=1)
y = df['Exam_Score']
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

In [59]:
model = keras.Sequential([
    layers.Dense(40, activation='relu'),
    layers.Dense(30, activation='relu'),
    layers.Dense(100, activation='relu'),
    layers.Dense(50, activation='relu'),
    layers.Dense(1, activation='linear')
])

In [60]:
model.compile(
    optimizer='adam',
    loss='mae',
    metrics=['mse']
)

In [61]:
X_train_processed = pd.get_dummies(X_train, drop_first=True)
X_valid_processed = pd.get_dummies(X_valid, drop_first=True)

history = model.fit(
    X_train_processed.astype('float32'), y_train,
    validation_data=(X_valid_processed.astype('float32'), y_valid),
    batch_size=10,
    epochs=30
)

Epoch 1/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 11.3885 - mse: 412.3297 - val_loss: 3.1386 - val_mse: 17.9196
Epoch 2/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 3.1852 - mse: 19.3076 - val_loss: 2.7474 - val_mse: 13.6487
Epoch 3/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2.8711 - mse: 16.1476 - val_loss: 2.7829 - val_mse: 15.0644
Epoch 4/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 2.6715 - mse: 13.9603 - val_loss: 2.3967 - val_mse: 11.9670
Epoch 5/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2.6118 - mse: 13.2966 - val_loss: 2.3798 - val_mse: 12.0269
Epoch 6/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 2.4887 - mse: 13.5324 - val_loss: 2.1004 - val_mse: 9.6287
Epoch 7/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 2.2959 - mse: 12.0256 - val_loss: 2.3776 - val_mse: 11.8874
Epoch 8/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.2574 - mse: 11.3299 - val_loss: 2.0630 - val_mse: 8.7701
Epoch 9/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.1849 - mse: 11.1300 - val_loss: 1.8352 - val_mse: 7.9117
Epoch 10/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.0211 - mse: 10.0121 - val_loss: 1.7417 - val_mse: 7.6352
Epoch 11/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 2.0832 - mse: 11.0492 - val_loss: 1.6134 - val_mse: 6.9051
Epoch 12/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.7207 - mse: 7.7366 - val_loss: 1.6471 - val_mse: 6.6179
Epoch 13/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.7614 - mse: 9.3142 - val_loss: 1.4536 - val_mse: 5.7643
Epoch 14/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.5609 - mse: 6.6263 - val_loss: 1.2556 - val_mse: 5.4641
Epoch 15/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.3521 - mse: 6.6230 - val_loss: 1.0596 - val_mse: 4.6238
Epoch 16/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.2906 - mse: 7.5027 - val_loss: 1.1982 - val_mse: 5.2520
Epoch 17/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.1674 - mse: 6.0870 - val_loss: 0.8803 - val_mse: 3.9767
Epoch 18/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 1.1091 - mse: 5.8492 - val_loss: 1.4520 - val_mse: 5.0976
Epoch 19/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.9946 - mse: 6.7657 - val_loss: 0.8617 - val_mse: 3.8167
Epoch 20/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.8089 - mse: 5.6966 - val_loss: 0.5186 - val_mse: 3.4338
Epoch 21/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.7918 - mse: 5.7066 - val_loss: 0.5556 - val_mse: 3.4999
Epoch 22/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.7218 - mse: 6.0670 - val_loss: 0.5453 - val_mse: 3.5047
Epoch 23/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.6875 - mse: 4.0528 - val_loss: 0.7751 - val_mse: 3.5557
Epoch 24/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.7257 - mse: 5.9239 - val_loss: 0.5156 - val_mse: 3.2988
Epoch 25/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.6090 - mse: 4.0923 - val_loss: 0.4811 - val_mse: 3.3686
Epoch 26/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6677 - mse: 4.3646 - val_loss: 0.4737 - val_mse: 3.2824
Epoch 27/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6411 - mse: 5.4837 - val_loss: 1.2466 - val_mse: 4.2823
Epoch 28/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6800 - mse: 4.8556 - val_loss: 0.8959 - val_mse: 3.6967
Epoch 29/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6468 - mse: 5.1909 - val_loss: 0.4722 - val_mse: 3.3003
Epoch 30/30
529/529 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 0.6398 - mse: 4.9286 - val_loss: 0.4359 - val_mse: 3.3012

In [12]:
X_train_processed.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Parental_Involvement_Low,Parental_Involvement_Medium,Access_to_Resources_Low,Access_to_Resources_Medium,...,Teacher_Quality_Medium,School_Type_Public,Peer_Influence_Neutral,Peer_Influence_Positive,Learning_Disabilities_Yes,Parental_Education_Level_High School,Parental_Education_Level_Postgraduate,Distance_from_Home_Moderate,Distance_from_Home_Near,Gender_Male
5810,27,79,8,63,2,5,True,False,False,False,...,True,True,False,False,False,False,False,True,False,False
1268,16,86,7,94,2,3,False,False,False,True,...,False,True,True,False,False,True,False,True,False,False
414,22,87,8,83,1,1,True,False,False,True,...,True,True,True,False,False,False,False,False,False,True
4745,18,100,10,86,1,3,False,False,False,True,...,True,True,True,False,False,True,False,False,True,True
654,35,78,10,99,1,2,False,False,True,False,...,True,False,False,True,False,True,False,False,True,True

In [23]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression

In [25]:
lin = LinearRegression()
lin.fit(X_train_processed, y_train);

In [26]:
lin.predict(X_valid_processed)

array([64.54181834, 65.2376837 , 71.53676035, ..., 66.16912985,
       63.41131223, 71.74767381])

In [27]:
mean_absolute_error(y_valid, lin.predict(X_valid_processed))

0.45028541547009376

In [28]:
mean_squared_error(y_valid, lin.predict(X_valid_processed))

3.256695866435405