<a href="https://colab.research.google.com/github/DaniRodri17/dep/blob/main/keras_classification_liver_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import pandas as pd
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error
from sklearn.ensemble import RandomForestClassifier
from tensorflow.keras.callbacks import EarlyStopping

In [127]:
df = pd.read_csv('Testing_indian_liver_disease_dataset.csv')
col_to_drop = ['Patient_ID', 'Occupation']
df.drop(col_to_drop, axis=1, inplace=True)
df.head()

,Age,Gender,BMI,Obesity_Class,Diet_Quality,Physical_Activity,Sleep_Hours,Smoking_Status,Alcohol_Consumption,Sym_Fatigue,...,Comorb_Diabetes,Comorb_Hypertension,Comorb_Genetic_History,ALT,AST,Bilirubin,Albumin,Platelets,Alk_Phosphatase,Liver_Disease_Type
0,73,Male,30.6,Obesity I,Healthy,Sedentary,8.8,Never,NaN,0,...,0,1,0,56.26,85.85,2.19,3.98,294,111,Cirrhosis
1,35,Female,23.5,Normal,Healthy,Moderate,9.0,Never,Moderate,1,...,0,0,0,18.19,44.53,0.99,4.49,241,115,Normal
2,36,Female,25.3,Overweight,Healthy,Sedentary,6.8,Never,Low,0,...,1,0,0,25.47,40.20,0.34,4.72,319,117,Fatty_Liver
3,36,Male,15.0,Underweight,Healthy,Low,6.6,Never,NaN,0,...,0,0,0,54.57,42.13,0.69,3.48,170,99,Fatty_Liver
4,50,Female,30.0,Obesity I,Healthy,Low,6.3,Never,Moderate,1,...,0,1,0,15.00,34.57,1.00,3.51,329,119,Fatty_Liver

In [128]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='constant', fill_value=0)
df['Alcohol_Consumption'] = imputer.fit_transform(df[['Alcohol_Consumption']])[:, 0]
df['Alcohol_Consumption'].isna().sum()

np.int64(0)

In [142]:
X = df.drop('Liver_Disease_Type', axis=1)
y = df['Liver_Disease_Type']

X = pd.get_dummies(X, columns=object_columns, dtype='int')
y = pd.get_dummies(y, dtype='int')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train))
X_test = pd.DataFrame(scaler.transform(X_test))

In [133]:
y_test.head()

,Alcoholic_Liver_Disease,Cirrhosis,Fatty_Liver,Hepatitis_B,Hepatitis_C,Normal
1116,0,0,1,0,0,0
1368,1,0,0,0,0,0
422,0,0,1,0,0,0
413,0,0,1,0,0,0
451,0,0,1,0,0,0

In [143]:
model = Sequential([
    Dense(50, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.2),
    Dense(30, activation='relu'),
    Dropout(0.2),
    Dense(30, activation='relu'),
    Dropout(0.2),
    Dense(6, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['precision'])

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
history = model.fit(x=X_train, y=y_train,
                    validation_data=(X_test, y_test),
                    batch_size=100,
                    epochs=500,
                    callbacks=[early_stopping])

Epoch 1/500

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 1.8834 - precision: 0.2676 - val_loss: 1.6977 - val_precision: 0.0000e+00
Epoch 2/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7264 - precision: 0.3769 - val_loss: 1.5956 - val_precision: 0.0000e+00
Epoch 3/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.6208 - precision: 0.4153 - val_loss: 1.5077 - val_precision: 0.0000e+00
Epoch 4/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.5231 - precision: 0.5090 - val_loss: 1.4237 - val_precision: 0.7273
Epoch 5/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4388 - precision: 0.5821 - val_loss: 1.3455 - val_precision: 0.7750
Epoch 6/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3513 - precision: 0.6290 - val_loss: 1.2741 - val_precision: 0.7717
Epoch 7/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2640 - precision: 0.6877 - val_loss: 1.2118 - val_precision: 0.7704
Epoch 8/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.2224 - precision: 0.6779 - val_loss: 1.1570 - val_precision: 0.7737
Epoch 9/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1780 - precision: 0.7288 - val_loss: 1.1089 - val_precision: 0.7692
Epoch 10/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1253 - precision: 0.7627 - val_loss: 1.0617 - val_precision: 0.7668
Epoch 11/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0388 - precision: 0.7218 - val_loss: 1.0166 - val_precision: 0.7709
Epoch 12/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0235 - precision: 0.7586 - val_loss: 0.9763 - val_precision: 0.7880
Epoch 13/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9554 - precision: 0.7575 - val_loss: 0.9421 - val_precision: 0.7789
Epoch 14/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9254 - precision: 0.7581 - val_loss: 0.9064 - val_precision: 0.7730
Epoch 15/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9746 - precision: 0.7186 - val_loss: 0.8723 - val_precision: 0.7800
Epoch 16/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8663 - precision: 0.7909 - val_loss: 0.8464 - val_precision: 0.7742
Epoch 17/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.8693 - precision: 0.7513 - val_loss: 0.8168 - val_precision: 0.7830
Epoch 18/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8252 - precision: 0.7697 - val_loss: 0.7923 - val_precision: 0.7846
Epoch 19/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7711 - precision: 0.7786 - val_loss: 0.7691 - val_precision: 0.7868
Epoch 20/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7756 - precision: 0.8068 - val_loss: 0.7429 - val_precision: 0.7940
Epoch 21/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7542 - precision: 0.7861 - val_loss: 0.7138 - val_precision: 0.8053
Epoch 22/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7774 - precision: 0.7950 - val_loss: 0.7064 - val_precision: 0.8012
Epoch 23/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7337 - precision: 0.7816 - val_loss: 0.6902 - val_precision: 0.8114
Epoch 24/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6923 - precision: 0.8049 - val_loss: 0.6795 - val_precision: 0.8050
Epoch 25/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6411 - precision: 0.8383 - val_loss: 0.6768 - val_precision: 0.7919
Epoch 26/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.6601 - precision: 0.8027 - val_loss: 0.6600 - val_precision: 0.8047
Epoch 27/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6226 - precision: 0.8333 - val_loss: 0.6552 - val_precision: 0.8127
Epoch 28/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6954 - precision: 0.7923 - val_loss: 0.6417 - val_precision: 0.8123
Epoch 29/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6076 - precision: 0.8476 - val_loss: 0.6447 - val_precision: 0.8104
Epoch 30/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6639 - precision: 0.7953 - val_loss: 0.6323 - val_precision: 0.7985
Epoch 31/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.6495 - precision: 0.7801 - val_loss: 0.6240 - val_precision: 0.8060
Epoch 32/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.5734 - precision: 0.8462 - val_loss: 0.6291 - val_precision: 0.8071
Epoch 33/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.5893 - precision: 0.8359 - val_loss: 0.6118 - val_precision: 0.8191
Epoch 34/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6116 - precision: 0.8227 - val_loss: 0.5977 - val_precision: 0.8253
Epoch 35/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5643 - precision: 0.8423 - val_loss: 0.5951 - val_precision: 0.8180
Epoch 36/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5578 - precision: 0.8293 - val_loss: 0.6001 - val_precision: 0.8213
Epoch 37/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5519 - precision: 0.8220 - val_loss: 0.5923 - val_precision: 0.8238
Epoch 38/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5648 - precision: 0.8294 - val_loss: 0.5920 - val_precision: 0.8182
Epoch 39/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5300 - precision: 0.8253 - val_loss: 0.5886 - val_precision: 0.8171
Epoch 40/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5242 - precision: 0.8287 - val_loss: 0.5928 - val_precision: 0.8111
Epoch 41/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4816 - precision: 0.8470 - val_loss: 0.5915 - val_precision: 0.8087
Epoch 42/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4590 - precision: 0.8615 - val_loss: 0.5924 - val_precision: 0.8164
Epoch 43/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4990 - precision: 0.8486 - val_loss: 0.5882 - val_precision: 0.8164
Epoch 44/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4887 - precision: 0.8588 - val_loss: 0.5763 - val_precision: 0.8213
Epoch 45/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5366 - precision: 0.8221 - val_loss: 0.5797 - val_precision: 0.8208
Epoch 46/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4771 - precision: 0.8445 - val_loss: 0.5823 - val_precision: 0.8265
Epoch 47/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5065 - precision: 0.8430 - val_loss: 0.5809 - val_precision: 0.8230
Epoch 48/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4418 - precision: 0.8643 - val_loss: 0.5849 - val_precision: 0.8201
Epoch 49/500
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5361 - precision: 0.8381 - val_loss: 0.5877 - val_precision: 0.8182