<a href="https://colab.research.google.com/github/DaniRodri17/dep/blob/main/keras_classification_penguin_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error
from sklearn.ensemble import RandomForestClassifier

In [5]:
df = pd.read_csv('penguins_size.csv')
df.head()

  species     island  culmen_length_mm  ...  flipper_length_mm  body_mass_g     sex
0  Adelie  Torgersen              39.1  ...              181.0       3750.0    MALE
1  Adelie  Torgersen              39.5  ...              186.0       3800.0  FEMALE
2  Adelie  Torgersen              40.3  ...              195.0       3250.0  FEMALE
3  Adelie  Torgersen               NaN  ...                NaN          NaN     NaN
4  Adelie  Torgersen              36.7  ...              193.0       3450.0  FEMALE

[5 rows x 7 columns]

In [17]:
df.dropna(inplace=True)

In [72]:
X = df.drop('species', axis=1)
y = df['species']

# Apply one-hot encoding to categorical columns 'island' and 'sex'
X = pd.get_dummies(X, columns=['island', 'sex'], drop_first=True)

# Convert target variable 'species' to one-hot encoded format
y = pd.get_dummies(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [49]:
dt = RandomForestClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
print(accuracy_score(y_test, dt_pred))

0.9900990099009901

In [51]:
from sklearn.metrics import classification_report
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

      Adelie       0.98      1.00      0.99        49
   Chinstrap       1.00      0.94      0.97        18
      Gentoo       1.00      1.00      1.00        34

    accuracy                           0.99       101
   macro avg       0.99      0.98      0.99       101
weighted avg       0.99      0.99      0.99       101

In [52]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, dt_pred))
#

[[49  0  0]
 [ 1 17  0]
 [ 0  0 34]]

In [54]:
X_train.head()

     culmen_length_mm  culmen_depth_mm  ...  sex_FEMALE  sex_MALE
292              48.2             15.6  ...       False      True
302              47.4             14.6  ...        True     False
62               37.6             17.0  ...        True     False
181              52.8             20.0  ...       False      True
15               36.6             17.8  ...        True     False

[5 rows x 8 columns]

In [117]:
model = Sequential([
    Dense(512, activation='relu', input_shape=(8,)),
    Dense(312, activation='relu'),

    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['precision']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [118]:
history = model.fit(x=X_train, y=y_train,
                    validation_data=(X_test, y_test),
                    batch_size=10,
                    epochs=200)

Epoch 1/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 217.0810 - precision: 0.3393 - val_loss: 149.4727 - val_precision: 0.3366
Epoch 2/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 124.9061 - precision: 0.3098 - val_loss: 55.1778 - val_precision: 0.3366
Epoch 3/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 97.3375 - precision: 0.4081 - val_loss: 39.8577 - val_precision: 0.3366
Epoch 4/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.9203 - precision: 0.3718 - val_loss: 34.5790 - val_precision: 0.4851
Epoch 5/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 28.2314 - precision: 0.3828 - val_loss: 93.2910 - val_precision: 0.1782
Epoch 6/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 73.5738 - precision: 0.3098 - val_loss: 31.8778 - val_precision: 0.6634
Epoch 7/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30.7854 - precision: 0.3609 - val_loss: 11.0875 - val_precision: 0.4851
Epoch 8/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33.8468 - precision: 0.4534 - val_loss: 8.4464 - val_precision: 0.3762
Epoch 9/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 16.5072 - precision: 0.4456 - val_loss: 7.7264 - val_precision: 0.5149
Epoch 10/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 12.0417 - precision: 0.4635 - val_loss: 20.8170 - val_precision: 0.4158
Epoch 11/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16.1634 - precision: 0.5046 - val_loss: 19.8984 - val_precision: 0.3465
Epoch 12/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.0320 - precision: 0.4298 - val_loss: 6.1145 - val_precision: 0.6832
Epoch 13/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.4727 - precision: 0.4054 - val_loss: 44.2178 - val_precision: 0.3366
Epoch 14/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 33.9246 - precision: 0.4146 - val_loss: 16.8529 - val_precision: 0.5545
Epoch 15/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 10.5672 - precision: 0.6166 - val_loss: 15.2657 - val_precision: 0.4455
Epoch 16/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11.9411 - precision: 0.5892 - val_loss: 4.0003 - val_precision: 0.4752
Epoch 17/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.6764 - precision: 0.4407 - val_loss: 13.5474 - val_precision: 0.5050
Epoch 18/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.2900 - precision: 0.5735 - val_loss: 3.0989 - val_precision: 0.6634
Epoch 19/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.6087 - precision: 0.5322 - val_loss: 5.5866 - val_precision: 0.5248
Epoch 20/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8803 - precision: 0.5471 - val_loss: 15.5746 - val_precision: 0.4752
Epoch 21/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.2556 - precision: 0.5107 - val_loss: 17.5790 - val_precision: 0.5644
Epoch 22/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.1601 - precision: 0.6214 - val_loss: 24.7552 - val_precision: 0.3465
Epoch 23/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17.1904 - precision: 0.4606 - val_loss: 3.2646 - val_precision: 0.4950
Epoch 24/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.1717 - precision: 0.5048 - val_loss: 10.7826 - val_precision: 0.4851
Epoch 25/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.5291 - precision: 0.5300 - val_loss: 5.0546 - val_precision: 0.5644
Epoch 26/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6405 - precision: 0.5952 - val_loss: 5.6810 - val_precision: 0.7129
Epoch 27/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.5681 - precision: 0.4924 - val_loss: 13.2946 - val_precision: 0.6337
Epoch 28/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17.3604 - precision: 0.5397 - val_loss: 18.2237 - val_precision: 0.4059
Epoch 29/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11.6038 - precision: 0.5647 - val_loss: 6.7755 - val_precision: 0.4851
Epoch 30/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.9211 - precision: 0.6693 - val_loss: 4.4823 - val_precision: 0.4851
Epoch 31/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.3214 - precision: 0.6962 - val_loss: 6.8524 - val_precision: 0.5446
Epoch 32/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8401 - precision: 0.5062 - val_loss: 7.7977 - val_precision: 0.4950
Epoch 33/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 14.3083 - precision: 0.4649 - val_loss: 3.9407 - val_precision: 0.7624
Epoch 34/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.4255 - precision: 0.7143 - val_loss: 7.1051 - val_precision: 0.4950
Epoch 35/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.1796 - precision: 0.4707 - val_loss: 2.1452 - val_precision: 0.7327
Epoch 36/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.9076 - precision: 0.6780 - val_loss: 1.4059 - val_precision: 0.7723
Epoch 37/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6709 - precision: 0.5868 - val_loss: 3.2323 - val_precision: 0.4257
Epoch 38/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.1169 - precision: 0.6647 - val_loss: 3.0345 - val_precision: 0.7129
Epoch 39/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.3567 - precision: 0.6275 - val_loss: 4.1445 - val_precision: 0.4950
Epoch 40/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.2146 - precision: 0.6085 - val_loss: 1.7662 - val_precision: 0.8713
Epoch 41/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.4601 - precision: 0.6092 - val_loss: 1.8048 - val_precision: 0.7327
Epoch 42/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.5305 - precision: 0.6862 - val_loss: 6.7409 - val_precision: 0.4851
Epoch 43/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.7477 - precision: 0.5414 - val_loss: 26.9966 - val_precision: 0.3762
Epoch 44/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.0820 - precision: 0.5589 - val_loss: 10.2610 - val_precision: 0.7129
Epoch 45/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.5491 - precision: 0.6308 - val_loss: 5.1241 - val_precision: 0.7129
Epoch 46/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.0588 - precision: 0.6178 - val_loss: 0.6458 - val_precision: 0.9307
Epoch 47/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.6101 - precision: 0.6413 - val_loss: 3.8473 - val_precision: 0.6634
Epoch 48/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.8948 - precision: 0.6316 - val_loss: 0.5838 - val_precision: 0.9307
Epoch 49/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11.8010 - precision: 0.5537 - val_loss: 3.1731 - val_precision: 0.4059
Epoch 50/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.2132 - precision: 0.6367 - val_loss: 2.7456 - val_precision: 0.6832
Epoch 51/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.0779 - precision: 0.4316 - val_loss: 11.1029 - val_precision: 0.5050
Epoch 52/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.0741 - precision: 0.6841 - val_loss: 4.0531 - val_precision: 0.7525
Epoch 53/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.0588 - precision: 0.6195 - val_loss: 3.9178 - val_precision: 0.7426
Epoch 54/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.4065 - precision: 0.6077 - val_loss: 0.5549 - val_precision: 0.9307
Epoch 55/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4746 - precision: 0.8363 - val_loss: 5.5517 - val_precision: 0.4950
Epoch 56/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.9996 - precision: 0.7446 - val_loss: 1.9259 - val_precision: 0.7723
Epoch 57/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.6584 - precision: 0.6860 - val_loss: 7.8843 - val_precision: 0.6931
Epoch 58/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1745 - precision: 0.5468 - val_loss: 7.0565 - val_precision: 0.6931
Epoch 59/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.5581 - precision: 0.6168 - val_loss: 0.5011 - val_precision: 0.9208
Epoch 60/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.8821 - precision: 0.8435 - val_loss: 2.5168 - val_precision: 0.4950
Epoch 61/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.6807 - precision: 0.6443 - val_loss: 11.7251 - val_precision: 0.4700
Epoch 62/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.6927 - precision: 0.5306 - val_loss: 14.3488 - val_precision: 0.4851
Epoch 63/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 12.8702 - precision: 0.4656 - val_loss: 6.9659 - val_precision: 0.5050
Epoch 64/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.1496 - precision: 0.4682 - val_loss: 1.9831 - val_precision: 0.7723
Epoch 65/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.3347 - precision: 0.6522 - val_loss: 3.5872 - val_precision: 0.4851
Epoch 66/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9999 - precision: 0.5632 - val_loss: 8.3023 - val_precision: 0.5050
Epoch 67/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.4774 - precision: 0.5621 - val_loss: 12.4613 - val_precision: 0.4851
Epoch 68/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.0854 - precision: 0.4389 - val_loss: 1.0919 - val_precision: 0.7327
Epoch 69/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.9418 - precision: 0.6323 - val_loss: 2.8194 - val_precision: 0.5152
Epoch 70/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.7519 - precision: 0.6230 - val_loss: 1.7574 - val_precision: 0.5700
Epoch 71/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.6433 - precision: 0.7091 - val_loss: 2.7770 - val_precision: 0.7327
Epoch 72/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.0733 - precision: 0.6677 - val_loss: 1.0706 - val_precision: 0.7426
Epoch 73/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0576 - precision: 0.7878 - val_loss: 0.3684 - val_precision: 0.9505
Epoch 74/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3422 - precision: 0.6881 - val_loss: 2.3063 - val_precision: 0.7624
Epoch 75/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.0412 - precision: 0.6680 - val_loss: 0.6127 - val_precision: 0.9208
Epoch 76/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4013 - precision: 0.7158 - val_loss: 0.4196 - val_precision: 0.9109
Epoch 77/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2946 - precision: 0.7192 - val_loss: 1.5590 - val_precision: 0.5900
Epoch 78/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.4570 - precision: 0.6844 - val_loss: 1.0693 - val_precision: 0.6667
Epoch 79/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.5112 - precision: 0.7199 - val_loss: 0.3226 - val_precision: 0.9307
Epoch 80/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1971 - precision: 0.7303 - val_loss: 2.4394 - val_precision: 0.7129
Epoch 81/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.6197 - precision: 0.7112 - val_loss: 0.3248 - val_precision: 0.9208
Epoch 82/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9840 - precision: 0.7877 - val_loss: 1.2576 - val_precision: 0.5446
Epoch 83/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.9891 - precision: 0.6638 - val_loss: 0.5208 - val_precision: 0.8020
Epoch 84/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7044 - precision: 0.7470 - val_loss: 0.3746 - val_precision: 0.8911
Epoch 85/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8126 - precision: 0.7494 - val_loss: 0.8548 - val_precision: 0.7723
Epoch 86/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.3067 - precision: 0.6459 - val_loss: 0.8112 - val_precision: 0.6535
Epoch 87/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9750 - precision: 0.6970 - val_loss: 1.1970 - val_precision: 0.7228
Epoch 88/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9365 - precision: 0.7873 - val_loss: 0.3919 - val_precision: 0.9010
Epoch 89/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2732 - precision: 0.7393 - val_loss: 0.5914 - val_precision: 0.8020
Epoch 90/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.7808 - precision: 0.7189 - val_loss: 0.7641 - val_precision: 0.7000
Epoch 91/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2630 - precision: 0.7841 - val_loss: 1.5776 - val_precision: 0.7624
Epoch 92/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.2703 - precision: 0.6560 - val_loss: 0.5879 - val_precision: 0.9300
Epoch 93/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.2119 - precision: 0.7446 - val_loss: 0.2535 - val_precision: 0.9208
Epoch 94/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4165 - precision: 0.7778 - val_loss: 0.2529 - val_precision: 0.9505
Epoch 95/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4328 - precision: 0.8887 - val_loss: 0.7781 - val_precision: 0.6800
Epoch 96/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5480 - precision: 0.8072 - val_loss: 1.0344 - val_precision: 0.7921
Epoch 97/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.5912 - precision: 0.6599 - val_loss: 0.2600 - val_precision: 0.9406
Epoch 98/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6786 - precision: 0.8090 - val_loss: 0.5599 - val_precision: 0.8020
Epoch 99/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0107 - precision: 0.7120 - val_loss: 0.4072 - val_precision: 0.8515
Epoch 100/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5659 - precision: 0.8288 - val_loss: 0.3533 - val_precision: 0.9505
Epoch 101/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3933 - precision: 0.8580 - val_loss: 0.6369 - val_precision: 0.8119
Epoch 102/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7660 - precision: 0.7830 - val_loss: 0.4946 - val_precision: 0.9109
Epoch 103/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9676 - precision: 0.7999 - val_loss: 0.5371 - val_precision: 0.7921
Epoch 104/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4121 - precision: 0.7169 - val_loss: 0.2701 - val_precision: 0.9505
Epoch 105/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0042 - precision: 0.7598 - val_loss: 0.1968 - val_precision: 0.9703
Epoch 106/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5708 - precision: 0.8004 - val_loss: 1.1364 - val_precision: 0.8119
Epoch 107/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7364 - precision: 0.8021 - val_loss: 0.6802 - val_precision: 0.8119
Epoch 108/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0715 - precision: 0.6554 - val_loss: 0.2334 - val_precision: 0.9208
Epoch 109/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1459 - precision: 0.7976 - val_loss: 0.5846 - val_precision: 0.8614
Epoch 110/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4827 - precision: 0.9124 - val_loss: 0.2196 - val_precision: 0.9208
Epoch 111/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1741 - precision: 0.7222 - val_loss: 0.1635 - val_precision: 0.9703
Epoch 112/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0576 - precision: 0.8365 - val_loss: 0.4032 - val_precision: 0.8317
Epoch 113/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.9025 - precision: 0.7675 - val_loss: 0.2974 - val_precision: 0.9505
Epoch 114/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0606 - precision: 0.6983 - val_loss: 0.3824 - val_precision: 0.8416
Epoch 115/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6869 - precision: 0.8317 - val_loss: 0.1841 - val_precision: 0.9406
Epoch 116/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 1.5078 - precision: 0.7531 - val_loss: 3.8454 - val_precision: 0.5446
Epoch 117/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.3453 - precision: 0.5891 - val_loss: 0.3020 - val_precision: 0.8911
Epoch 118/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8890 - precision: 0.8189 - val_loss: 0.6961 - val_precision: 0.8812
Epoch 119/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2584 - precision: 0.8928 - val_loss: 1.1060 - val_precision: 0.6970
Epoch 120/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2831 - precision: 0.7673 - val_loss: 0.8619 - val_precision: 0.8400
Epoch 121/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2054 - precision: 0.7465 - val_loss: 1.2649 - val_precision: 0.8020
Epoch 122/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2103 - precision: 0.7866 - val_loss: 1.1466 - val_precision: 0.7921
Epoch 123/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.5062 - precision: 0.5841 - val_loss: 1.9493 - val_precision: 0.4653
Epoch 124/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.0719 - precision: 0.5203 - val_loss: 2.6510 - val_precision: 0.5758
Epoch 125/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.4781 - precision: 0.6156 - val_loss: 1.4853 - val_precision: 0.8119
Epoch 126/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5377 - precision: 0.7090 - val_loss: 0.8770 - val_precision: 0.6337
Epoch 127/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8909 - precision: 0.7719 - val_loss: 0.1818 - val_precision: 0.9406
Epoch 128/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.5831 - precision: 0.8788 - val_loss: 0.9316 - val_precision: 0.6436
Epoch 129/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6878 - precision: 0.7748 - val_loss: 0.4246 - val_precision: 0.8500
Epoch 130/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6176 - precision: 0.8442 - val_loss: 0.2901 - val_precision: 0.9109
Epoch 131/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4884 - precision: 0.8467 - val_loss: 2.2897 - val_precision: 0.5149
Epoch 132/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9787 - precision: 0.7512 - val_loss: 0.2792 - val_precision: 0.8416
Epoch 133/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.3612 - precision: 0.6843 - val_loss: 1.5515 - val_precision: 0.7921
Epoch 134/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0884 - precision: 0.7838 - val_loss: 0.2435 - val_precision: 0.9604
Epoch 135/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4073 - precision: 0.8801 - val_loss: 0.6746 - val_precision: 0.8911
Epoch 136/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4048 - precision: 0.8725 - val_loss: 0.1453 - val_precision: 0.9505
Epoch 137/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2897 - precision: 0.9218 - val_loss: 1.2316 - val_precision: 0.7921
Epoch 138/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1862 - precision: 0.7678 - val_loss: 1.2398 - val_precision: 0.7921
Epoch 139/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.4429 - precision: 0.7146 - val_loss: 1.6311 - val_precision: 0.7921
Epoch 140/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.7362 - precision: 0.7607 - val_loss: 1.7109 - val_precision: 0.5545
Epoch 141/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6547 - precision: 0.8095 - val_loss: 0.1400 - val_precision: 0.9802
Epoch 142/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9444 - precision: 0.7607 - val_loss: 2.6748 - val_precision: 0.5050
Epoch 143/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2281 - precision: 0.7392 - val_loss: 0.1197 - val_precision: 0.9703
Epoch 144/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2169 - precision: 0.9353 - val_loss: 0.7508 - val_precision: 0.8400
Epoch 145/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8361 - precision: 0.7817 - val_loss: 0.1287 - val_precision: 0.9802
Epoch 146/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2845 - precision: 0.7200 - val_loss: 0.9681 - val_precision: 0.7071
Epoch 147/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2516 - precision: 0.7362 - val_loss: 0.1627 - val_precision: 0.9307
Epoch 148/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5396 - precision: 0.8037 - val_loss: 0.1915 - val_precision: 0.9604
Epoch 149/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3432 - precision: 0.8940 - val_loss: 0.1068 - val_precision: 0.9703
Epoch 150/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2605 - precision: 0.9068 - val_loss: 0.2866 - val_precision: 0.8900
Epoch 151/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4650 - precision: 0.8716 - val_loss: 0.1109 - val_precision: 0.9800
Epoch 152/200
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3657 - precision: 0.9104 - val_loss: 0.2758 - val_precision: 0.9500
Epoch 153/200